チャット画面
ichinana17/ChatSpace pull request #1
Opened 2019-01-12 12:07 UTC by ichinana17

チャット画面作成しました

2019-01-12 13:07 UTC, ichinana17 commented
<img width="1440" alt="2019-01-12 22 04 22" src="https://user-images.githubusercontent.com/45912184/51073584-607a5680-16b6-11e9-828c-d215e9ec73cc.png">

2019-01-14 02:06 UTC, takebn26 requested changes

2019-01-14 02:06 UTC, takebn26 commented on app/assets/stylesheets/_chat.scss
> +$sidehead-color: #253141;
変数はvariable.scssなど作ってそこで管理しapplication.scssで呼び出すようにしましょう

2019-01-14 02:06 UTC, takebn26 commented on app/assets/stylesheets/_chat.scss
> +h1 {
これから付け足す全てのh1要素が全てこのcssが当たってしまうためネストさせクラスを付与したいです

2019-01-14 02:06 UTC, takebn26 commented on app/assets/stylesheets/_chat.scss
> +h2 {
これから付け足す全てのh2要素が全てこのcssが当たってしまうためネストさせクラスを付与したいです

2019-01-14 02:06 UTC, takebn26 commented on app/assets/stylesheets/_chat.scss
> +h3 {
これから付け足す全てのh3要素が全てこのcssが当たってしまうためネストさせクラスを付与したいです

2019-01-14 02:06 UTC, takebn26 commented on app/assets/stylesheets/_chat.scss
> +footer {
基本要素そのものにcssを当てずにclassを使いましょう

2019-01-14 02:06 UTC, takebn26 commented on app/assets/stylesheets/application.scss
> +@import "font-awesome";
こちらは一番最初に読み込まないと_chat.scssなどで使った場合に表示されません

2019-01-16 12:19 UTC, ichinana17 commented on app/assets/stylesheets/application.scss
> +@import "font-awesome";
修正しました

2019-01-16 12:33 UTC, ichinana17 commented on app/assets/stylesheets/_chat.scss
> +h1 {
修正しました

2019-01-16 12:33 UTC, ichinana17 commented on app/assets/stylesheets/_chat.scss
> +h2 {
修正しました

2019-01-16 12:38 UTC, ichinana17 commented on app/assets/stylesheets/_chat.scss
> +h3 {
修正しました

2019-01-16 12:54 UTC, ichinana17 commented on app/assets/stylesheets/_chat.scss
> +h3 {
修正しました

2019-01-16 12:55 UTC, ichinana17 commented on app/assets/stylesheets/_chat.scss
> +footer {
修正しました

2019-01-16 12:56 UTC, ichinana17 commented
修正しました

2019-01-16 12:56 UTC, merged